Transfer psylink and abilities
Tachyonite/Pawnmorpher pull request #709
Opened 2022-09-23 16:50 UTC by Diakon5

Draft. Psylink Hediff is currently transfered successfully, adjusted hediff transfer to copy over Hediff's severity(or level if it's a leveled hediff). Ability copying doesn't work yet

2022-09-23 17:25 UTC, Diakon5 commented
Vanilla Psycasts Expanded breaks the Psylink transfer. Because of that, any pawn with a psylink can never fully transform into an animal.

2022-09-24 11:27 UTC, Zeracronius approved these changes

2022-09-24 13:00 UTC, Diakon5 commented
Closes #430.
Incompatibilty with Vanilla Psycasts Expanded reduced to a minor state, Now any Psycaster will retain their psylink but loses their psypowers. Reload may solve it, more explicit compatibility on the way.

2022-09-25 07:28 UTC, Diakon5 commented
Final commit. Now transformation only causes a single letter confirming the pawn has gained their first psylink. No messages for level-ups. Probably the best I can do without Harmony.

2022-09-25 14:37 UTC, Zeracronius commented on Source/Pawnmorphs/Esoteria/PawnTransferUtilities.cs
>                  health2.AddHediff(newHediff);
Hediff_Psylink has a public field called "suppressPostAddLetter"
though a bit fiddly, you could try set that to false between making and adding the hediff if psylink
that might well get rid of the last letter

2022-09-25 22:04 UTC, Zeracronius requested changes

2022-09-25 22:04 UTC, Zeracronius commented on Source/Pawnmorphs/Esoteria/PawnTransferUtilities.cs
> +                }
All of this code is basically identical to what is further below.
Could merge this if you handle "Find or Make + Suppress & add" and then handle severity adjustments

2022-09-26 07:07 UTC, Diakon5 commented on Source/Pawnmorphs/Esoteria/PawnTransferUtilities.cs
> +>>>>>>> Stashed changes
I don't know what caused it

2022-09-26 07:19 UTC, closed without merging